server:
  port: 9001

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 10.0.0.129:1111 #配置集群Nacos

management:
  endpoints:
    web:
      exposure:
        include: '*'

